### ISSUE TITLE
dorny/test-reporter fails with error when there is test failure.

### ISSUE THREAD

**Issue by Anudeep33** [dorny/test-reporter#241]
dorny/test-reporter fails with error when there is test failure.

Error: TypeError: stackTrace.split is not a function
below is junit.xml file

`<testsuites id="" name="" tests="1" failures="1" skipped="0" errors="0" time="73.49204799999995">
<testsuite name="frontend/login/login.test.ts" timestamp="1679684078841" hostname="" tests="1" failures="1" skipped="0" time="66.986" errors="0">
<testcase name="@login @RTA-83 Verify user is able to log in with an admin account @sanity @mobile" classname="[Chrome] › frontend/login/login.test.ts › @login › @RTA-83 Verify user is able to log in with an admin account @sanity @mobile" time="66.986">
<failure message="login.test.ts:39:5 @RTA-83 Verify user is able to log in with an admin account @sanity @mobile" type="FAILURE">
<![CDATA[  [Chrome] › frontend/login/login.test.ts:39:5 › @login › @RTA-83 Verify user is able to log in with an admin account @sanity @mobile 

    locator.waitFor: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[data-testid="summary-Offline"]" to be visible
    ============================================================

       at ../page/OverviewPage.ts:64

      62 |
      63 |     async verifyOverviewPageElements() {
    > 64 |         await this.page.locator(this.offlineSummarySelector).waitFor();
         |                                                              ^
      65 |         await this.page.locator(this.onlineSummarySelector).waitFor();
      66 |         await expect(this.onlineSummary).toHaveText("Online");
      67 |         await expect(this.offlineSummary).toHaveText("Offline");

        at OverviewPage.verifyOverviewPageElements (/qa-automation/test/frontend/login/login.test.ts:41:34

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome/test-failed-1.png
    ------------------------------------------------------------------------------------------------

    Retry #1 ---------------------------------------------------------------------------------------

    locator.waitFor: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[data-testid="summary-Offline"]" to be visible
    ============================================================

       at ../page/OverviewPage.ts:64

      62 |
      63 |     async verifyOverviewPageElements() {
    > 64 |         await this.page.locator(this.offlineSummarySelector).waitFor();
         |                                                              ^
      65 |         await this.page.locator(this.onlineSummarySelector).waitFor();
      66 |         await expect(this.onlineSummary).toHaveText("Online");
      67 |         await expect(this.offlineSummary).toHaveText("Offline");

        at OverviewPage.verifyOverviewPageElements (/qa-automation/test/frontend/login/login.test.ts:41:34

    attachment #1: trace (application/zip) ---------------------------------------------------------
    test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome-retry1/trace.zip
    Usage:

        npx playwright show-trace test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome-retry1/trace.zip

    ------------------------------------------------------------------------------------------------

    attachment #2: screenshot (image/png) ----------------------------------------------------------
    test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome-retry1/test-failed-1.png
    ------------------------------------------------------------------------------------------------
]]>
</failure>
<system-out>
<![CDATA[
[[ATTACHMENT|../test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome/test-failed-1.png]]

[[ATTACHMENT|../test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome-retry1/trace.zip]]

[[ATTACHMENT|../test-results/frontend-login-login--login-RTA-83-Verify-user-is-able-to-log-in-with-an-admin-account-sanity-mobile-Chrome-retry1/test-failed-1.png]]
]]>
</system-out>
</testcase>
</testsuite>
</testsuites>`

**Comment by Karamann** [comment]
Try your luck by changing the reporter format to java-junit:

      - name: visualise-test-reports
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Reports
          path: /tests/*.xml
          reporter: java-junit

**Comment by agjini** [comment]
Hello,

I've seen the fix in v1.7.0 release (PR #258), so I tried using `dorny/test-reporter@v1.7.0` in my github action :

```
      - name: e2e test report
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: e2e tests
          path: e2e-junit.xml
          reporter: jest-junit
```

But I experiment the the same error :

```
Creating test report e2e tests
  Processing test results for check run e2e tests
  Error: Processing test results from e2e-junit.xml failed
Error: TypeError: stackTrace.split is not a function
```

Is there another case that causes the error ?

Here is my jest_junit file (generated with vitest) :

[junit.xml.tar.gz](https://github.com/dorny/test-reporter/files/13379450/junit.xml.tar.gz)

Thanks for your help

**Comment by jlukic** [comment]
Ran into this with Vitest results, using `java-junit` fixes it.

**Comment by jozefizso** [comment]
## Root Cause Analysis

In `src/parsers/jest-junit/jest-junit-parser.ts:88-89`, the parser extracts the failure message:

```ts
const message = tc.failure ? tc.failure[0] : tc.error ? tc.error[0] : 'unknown failure'
const details = typeof message === 'string' ? message : message['_']
```

The `failure` field type is `string[]`, but when xml2js parses XML with **attributes on `<failure>`** (like `message` and `type` attributes), the parsed element is an **object** instead of a plain string. For example:

```xml
<failure message="..." type="FAILURE">
  <![CDATA[stack trace text]]>
</failure>
```

xml2js produces `{ $: { message: "...", type: "FAILURE" }, _: "stack trace text" }` — an object, not a string.

The code handles this with `message['_']`. **However**, `details` can end up as `undefined` when the `<failure>` element has attributes but no text content, or when the structure does not match expectations.

When `details` is `undefined` (or a non-string), it gets passed to `getExceptionSource()` at `src/utils/node-utils.ts:10`, which calls `stackTrace.split(...)` — and since it is not a string, `.split` does not exist, causing the crash.

## Why `java-junit` works as a workaround

Users report switching to `reporter: java-junit` fixes the issue. The `java-junit` parser (`src/parsers/java-junit/java-junit-parser.ts:155`) has its own `exceptionThrowSource()` that handles the data flow differently and avoids this crash.

## Scope

This affects any JUnit XML producer that includes attributes on `<failure>` or `<error>` elements — Playwright, Vitest, Cypress, and pytest have all been reported.

## Recommended Fix

Fix in both places for defense in depth:

1. **`jest-junit-parser.ts:89`** — coalesce `details` to empty string:
   ```ts
   const details = typeof message === 'string' ? message : message['_'] ?? ''
   ```
2. **`node-utils.ts:10`** — add a type guard at the top of `getExceptionSource`:
   ```ts
   if (typeof stackTrace !== 'string') return undefined
   ```
